### ISSUE TITLE
LinkNYC-Ad-Production-Device-Data-Dump

### ISSUE THREAD

**Issue by jefftulsa** [seesawlabs/cortex-html5-base#21]
From Doug:

got another project for you guys: a dump of all production devices with all relevant data tied to each device

**Comment by cjsauer** [comment]
Fields to include:
>lets do cortex name, device id, cortex player version, hostname (internal state) , current strategy and connectivity status

**Comment by jefftulsa** [comment]
@cjsauer emailed Valerie to let her know this is ready for review.
