### ISSUE TITLE
US Open Campaign (Due 8/23)

### ISSUE THREAD

**Issue by ivanmorales** [seesawlabs/cortex-html5-base#28]
## Summary
![image](https://user-images.githubusercontent.com/244904/29375019-c99142ae-8270-11e7-902a-7b17917bce3b.png)

## Data feed
We can confirm the data feed has:
1. Bracket Location - "Men's Singles Quarter Finals"
2. Player First Initial and Last Name
3. Player Country Abbreviation
4. Current Score
5. Who is serving - "Yellow line above J Sock"
6. Player ranking (optional)

### DataSet ID
`com.intersection.media.campaigns.usopenscores`

### Women's
https://drive.google.com/open?id=0B_-oXa1h4St8RUFhN0swSmxSMTA

### Men's
https://drive.google.com/open?id=0B_-oXa1h4St8WUZMX3ZvbE02Y0U

## Notes
- marketing said that player ranking is nice to have but not need to have, so do whatever you can
- make two separate bundles for men's and women's. we're going to daypart them to the average lengths of men's and women's matches + a little buffer time
- Due Date: 8/28
- rotate with the active games, no special template for final scores
- placeholder can be any linknyc general announcements creative

**Comment by jefftulsa** [comment]
@manuelrojas needs test data from @cjsauer
