### ISSUE TITLE
GoHealth Take 2 - Oct 2nd

### ISSUE THREAD

**Issue by jefftulsa** [seesawlabs/cortex-html5-base#39]
i have returned from the europe! hi! here is the new gohealth key: 4H9q215KkzuToMzl
these links don't work for me, let me know if you don't work for you either:  
API:
Prod documentation: http://www.gohealthuc.com/api/docs/
Staging documentation: https://www.gohealthuc.com/apistage/docs/
if they don't*
here's the list of site IDs they have and the gohealth location they would like them to refer to

the 9 non-staten island gohealth locations are paired with unique lists of site IDs, no overlap, while the staten island site IDs can rotate information regarding any of the 3 staten island gohealth locations so we're thinking of 10 unique bundles in total. does that work?
still waiting on creatives

[LinkNYC-LocationList-GoHealth-10.2.xlsx](https://github.com/seesawlabs/cortex-html5-base/files/1324946/LinkNYC-LocationList-GoHealth-10.2.xlsx)

**Comment by jefftulsa** [comment]
they want to have separate bundles for each location @ivanmorales

**Comment by cjsauer** [comment]
@jefftulsa I have an outstanding question for Erika right now. I'll copy here for posterity:

>Question on the GoHealth creative: with these 10 creatives, will you guys be handling the Vistar magic to make sure they only play on the proper devices? For example, the Staten Island creative will _only_ be scheduled to run on State Island devices. Or will these creatives play on _all_ devices in NYC, and we'll just show a placeholder for devices that aren't assigned to a clinic?

This will affect the way I code the importer a bit.

**Comment by cjsauer** [comment]
Erika replied:

>we'll make sure that the staten island bundle only goes on the staten island screens, that bundle number 1 only goes on the screens around the gohealth location Link number 1 etc
